### ISSUE TITLE
What do I assign to 'meta'?

### ISSUE THREAD

**Issue by nickpreston24** [file2html/file2html#1]
Hi, I'm trying to run your usage case you outlined.  I've got all 4 modules installed (npm) just fine with no issues, but I'm still at a loss as to what is assigned to the **meta** value you specified.  Here is my code so far:

```
const letterPath = './assets/rtf/SampleLetter.rtf'
const file2html = require('file2html')
const TextReader = require('file2html-text');
const OOXMLReader = require('file2html-ooxml');
const ImageReader = require('file2html-image');

function file2HtmlSample() {
    file2html.config({
        readers: [
            TextReader,
            OOXMLReader,
            ImageReader
        ]
    });

    var fileBuffer = fs.ReadStream(letterPath)
    var meta = {}

    file2html.read({
        fileBuffer,
        meta
    }).then((file) => {
        const {
            styles,
            content
        } = file.getData();
        // document.body.innerHTML = styles + content;
        console.log('file2Html-sample:\n', styles + content);
    });
}
```

**Comment by webschik** [comment]
Hi Mike!

It's an object with optional [FileMetaInformation](https://github.com/file2html/file2html#filemetainformation)

`file2html` tries to collect all meta information from the file: `size`, `mimeType`, `name`, etc., see [FileMetaInformation](https://github.com/file2html/file2html#filemetainformation) interface.
But you may override those properties by passing `meta` object to the `file2html.read` method.

BTW, RTF is not supported yet. Please, check all supported formats in [this list](https://github.com/file2html/file2html#supported-formats)

**Comment by nickpreston24** [comment]
Hi, I've deleted the 'meta' object and changed my file to be a docx, but I'm still having issues:

> C:\Users\Nick\Desktop\TPOT Dev\TPOT Electron\node_modules\file2html\lib\index.js:44 Uncaught TypeError: Cannot read property 'mimeType' of undefined
>     at C:\Users\Nick\Desktop\TPOT Dev\TPOT Electron\node_modules\file2html\lib\index.js:44:56
>     at Array.find (native)
>     at Object.read (C:\Users\Nick\Desktop\TPOT Dev\TPOT Electron\node_modules\file2html\lib\index.js:43:37)
>     at Object.file2HtmlSample (C:\Users\Nick\Desktop\TPOT Dev\TPOT Electron\assets\js\test-modules\RtfConverter.js:53:15)
>     at window.onload (file:///C:/Users/Nick/Desktop/TPOT%20Dev/TPOT%20Electron/assets/js/letters.js:52:15)

I think this tells me that meta still needs to be passed in and is not optional.  That, or the mimetype is not collected automatically for docx?  Not sure.  Thanks.

**Comment by nickpreston24** [comment]
Separate issue, but I'll leave it here.  You've said FileMetaData is an interface, so I think of java/C# interfaces.  Do I derive from it?  Or is it a JSON object?  It looks like the latter, as JS is weak typed and has no interfaces.

If trying to use File, what does that refer to?  I really have no idea.  Is it something like this: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/getMetadata ?

My assumption is that your module is using filestream also (doesn't complain about it so far), so my natural inclination as to what 'File' means is that it's from the FileSystem module or something else.

I'm using npm, so I'm also doing the following:
`const fs = require('fs')`

Thanks!

**Comment by webschik** [comment]
Hi Mike!

1) file2html does not parse the mime types from the file content. Try to pass an object as `meta` with correct `mimeType` property. I will fix the docs later

2.1) This module is written in Typesript, with transpilation to pure JS. Typesript interfaces are very similar to C# https://www.typescriptlang.org/docs/handbook/interfaces.html

2.2) [File](https://github.com/file2html/file2html/blob/master/README.md#file) is a custom interface for the Promise value from .read() method

**Comment by nickpreston24** [comment]
I'm still getting an Uncaught TypeError, which takes me to index.js:44.
![image](https://user-images.githubusercontent.com/9275026/43308070-e3649228-9145-11e8-9516-481f9040e586.png)

Code:
```
function file2HtmlSample() {
    file2html.config({
        readers: [
            TextReader,
            OOXMLReader,
            ImageReader
        ]
    });

    var fileBuffer = fs.ReadStream(letterPath)
    var meta = {
        mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    }

    file2html.read({
        fileBuffer,
        meta // : FileMetaInformation
    }).then((file) => {
        const {
            styles,
            content
        } = file.getData();
        // document.body.innerHTML = styles + content;
        console.log('file2Html-sample:\n', styles + content);
    });
}
```

Could I have a full example usage of FileMetaInformation?  I checked out the link you gave for Typescript and tried to emulate the Optional Parameters, with no success.

Later, after this bug, I managed to brick my project entirely by installing the ooxml engine (npm i file2html-ooxml) a second time.  Perhaps that's just a Node /Electron thing, idk.

**Comment by webschik** [comment]
@MikePreston17, https://gist.github.com/webschik/ff65ca94d9d6eaa1bcf05d748d9eeaf8
