### ISSUE TITLE
example demo

### ISSUE THREAD

**Issue by baltun** [file2html/file2html#2]
where is it possible to look example demo of how library works?

**Comment by webschik** [comment]
Hi, 

Unfortunately, there is no REPL or online demo with this library.

This extension - https://chrome.google.com/webstore/detail/stormfiles/ickghndjocahgacnfaakbmbokmfneahd was built using this library and all [file2html engines](https://github.com/file2html)

Also, check how to install & configure this library - https://github.com/file2html/file2html#installation
